#!/bin/sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

pattern='^(feat|fix|docs|refactor|test|style|chore|ci)(\(#?[0-9]+\))?: .+$'

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
    echo ""
    echo "❌ Invalid commit message."
    echo ""
    echo "Expected format:"
    echo "  feat: add project analyzer"
    echo "  feat(#12): add project analyzer"
    echo "  fix: resolve docker parser"
    echo ""
    exit 1
fi

exit 0