FROM eclipse-temurin:{{ .RuntimeVersion }}-jdk AS builder

WORKDIR /workspace
COPY . .
RUN {{ .BuildCommand }}

FROM eclipse-temurin:{{ .RuntimeVersion }}-jre

WORKDIR /app
COPY --from=builder /workspace/{{ .ArtifactPath }} app.jar

EXPOSE {{ .ApplicationPort }}

ENTRYPOINT ["java", "-jar", "app.jar"]